name: Participate
description: Register to compete as a team or individual
title: "new registration"
labels: [participant]
assignees: [casperdcl]
body:
- type: input
  id: name
  attributes:
    label: Team Name
    description: Under what name would you like to compete? Spaces not allowed.
    placeholder: e.g. PETrified-Becquerels
- type: input
  id: users
  attributes:
    label: GitHub users
    description: Any teammates who want read/write access to your team's repository.
    placeholder: Optional
- type: checkboxes
  id: terms
  attributes:
    label: Terms
    options:
    - label: (Optional) I want to be eligible for prizes, and will make my code public after the challenge ends.
      required: false
    - label: I agree to abide by the [rules](https://github.com/SyneRBI/PETRIC/wiki).
      required: true
